### ISSUE TITLE
Freeze Timers Location

### ISSUE THREAD

**Issue by bigmemes420** [runeliteplusplus/RuneLitePlusPlus#10]
I noticed the location of the freeze timers is connected to where your camera is and isn't attached to the player that it is representing the freeze timer for.
The 
![javaw_2019-02-16_02-44-31](https://user-images.githubusercontent.com/38368432/53918456-9c81c600-402c-11e9-9b0f-5f7aeb7daadd.png)
![javaw_2019-02-16_02-44-38](https://user-images.githubusercontent.com/38368432/53918457-9c81c600-402c-11e9-9383-b4c8cecd263c.png)
Both of these images are on the same freeze and the only difference is where the camera is.

**Comment by runeliteplusplus** [comment]
To the best of my knowledge this is simply how RuneLite renders this type of overlay.

I tried experimenting with different values to try and get this to be more stable when I first released this plugin many months ago, to no success. Rotating the camera angle will skew any on canvas overlay, you can see this in the Zulrah plugin with the next phase tile markers. I guess it isn't such a big issue in vanilla RuneLite because no plugins make such overlays.

If any RuneLite professionals want to chime in and tell me if I'm missing something I'd be happy for the input, but it's more then likely this is just how RuneLite works.

Nonetheless, thank you for the bug hunting, bigmemes420.
