### ISSUE TITLE
How does clan plugin work?

### ISSUE THREAD

**Issue by Matt5432** [runeliteplusplus/RuneLitePlusPlus#5]
Hi , how does the clan plugin work?

**Comment by runeliteplusplus** [comment]
Hello,

There is a lot that can be improved in this plugin, however the way it currently works is:

Checks if you are within the wilderness, gathers the lowest and highest combat level of visible clan members (or just your own cb lvl if not in clan, very useful for solo deep wildy), and based on your current wilderness level, will highlight players accordingly that everyone in the clan can attack.

Things that someone else can improve:

- I've found in very large clan scenarios, it would be more effective to only highlight players relevant to your own character cb lvl instead of the entire clan, if there is a wide level difference within the clan.

- Calculate both your wilderness level AND the wilderness level of potential targets, as right now if you are north of someone it can appear they are attackable, but when you run south you no longer can.

- Reset the clan member array upon cc leave / join, as right now the only way of doing so is restarting the plugin.
