### ISSUE TITLE
Vorkrath/Zulrah feedback!

### ISSUE THREAD

**Issue by flewychan** [runeliteplusplus/RuneLitePlusPlus#7]
Hey, was trying out the zulrah plugin, seems to work fine although i think could add more stuff?

- Show what prayer to pray during Jad phase

- During pattern 2 (based on this zulrah rotation guide, pic #5) https://i.imgur.com/U4VPfbs.png, the tile marked is on the poison gas that zulrah spits out during mage phase

- Maybe Rigour/Augury support? 

- Also could make it so that it shows what to pray for next phase/current phase if you dont have right prayer selected

EDIT: tried vorkrath too, works awesome! Abit of feedback tho
- For the Poison Pool Quickfire Barrage phase, possibly highlight paths that are *safe* ? or 4-5 tiles long so player can quickly avoid any avoidable damage

Overall feedback:
- Hope that you can add for the indicators to show on screen (such as boosted stats on bottom right of screen etc) than above of the boss's hp, would make things easier since that not everyone plays the game fully zoomed out and if you didn't zoom out to see boss's hp, you cant see what to pray next (zulrah) or how many special attacks/quickfire barrages left (vorkrath).

Once again, thank you (and your team) for bringing/giving these amazing plugins another life !

**Comment by runeliteplusplus** [comment]
Hello, thank you for the many suggestions. I have pushed an update with the following:

- Zulrah jad phase prayer indicator. This hasn't been tested on every phase and there is a bug where after Zulrah is done attacking you and starts throwing toxic gas, the prayer indicator will keep changing because the animation ID is the same. The solution to this is counting jad phase attacks but this isn't something I can be bothered to do currently.

- Hydra plugin now supports option to hide all text overlay's and only show prayer indicator and counter in a box overlay.

- Vorkath now has option to show quickfire barrage / special attack counter in overlay box.

As for your other suggestions;

- I do not believe that marked tile is always in gas, only partway through the phase, there are multiple tiles where this happens, I just followed the markings of the Zulrah helper you linked and they are not 100% perfect, however minimal effort is needed to figure out when and where to move so I didn't consider this a major issue.

- I think it is self explanatory when you should pray offensive prayers, a helper for this would only add to onscreen 'plugin clutter'.

- This is accomplished with the next phase tile markers, I think anything additional would add to on screen clutter and only be minimally beneficial.

- While I can see how a tile highlight for Vorkath's quickfire barrage to show where to walk can have it's uses, I think the developmental effort outweighs the benefits.

**Comment by flewychan** [comment]
Holy crap! Didnt expect such a quick response from you. Will test the new features and update you on any issues.

Thanks for reading my other suggestions even though you arent implementing them, you're awesome!

edit: could you add what to pray for zulrah in overlay box too ?

**Comment by runeliteplusplus** [comment]
Hello,

Do you mean you want a pray overlay box like the jad phase currently has to be present all the time?

**Comment by zlez93** [comment]
Just wanted to say thanks for creating this.

**Comment by ghost** [comment]
I got around to using the Zulrah plugin. It's pretty good and I don't have any problem with it. I did notice that the tile highlights are geared towards a hybrid trident/blowpipe setup while I prefer the range only method so where I stand is slightly different.
