### ISSUE TITLE
Clan Man Mode not working

### ISSUE THREAD

**Issue by flewychan** [runeliteplusplus/RuneLitePlusPlus#9]
Tried using the CMM Plugin, it shows for like 1 - 2 seconds and disappears. 

Im in a CC

**Comment by runeliteplusplus** [comment]
Hello,

here is how the clan man mode plugin currently works: https://github.com/runeliteplusplus/RuneLitePlusPlus/issues/5

It definitely needs a re-work to be the plugin I envisioned, however can you describe your issue in more detail? Being in a CC isn't even a requirement.

**Comment by flewychan** [comment]
Yeah i thought you had to be in a CC for it to work, i tried it at revs, had everything enabled, but nothing was shown (attackable players or what not). I then turned it off and on again, this time attackable players were shown, but it only showed for like 1-2 seconds, then everything disappeared as if i didnt had the plugin turned on

**Comment by runeliteplusplus** [comment]
I think you just haven't used it enough to get a feel for how it works, since it worked after you turned it off and on I'm going to assume you were in the presence of clan members with a high combat level difference, and there wasn't anyone present that all members of the clan could attack.

I'll make an option to highlight based on your cb lvl instead of clan soon.

**Comment by runeliteplusplus** [comment]
Just pushed a big clan man mode update that includes the following:

- Option to remove attack option from clan members.
- Option to highlight clan members even when not in clan chat (so when CC breaks every other hop this will fix that).
- Now has option to highlight attackable targets based on the entire clans combat levels OR just your own.
- Now takes both your wilderness lvl and potential targets wilderness lvl into account to determine if they are attackable or not.

To reset the CC members array you need to restart the plugin, I think this is more beneficial then checking when you leave / join a CC because it will help with the broken CC issue that's recently been plaguing OSRS.
